version: "3.1"

services:
   omada-controller:
     container_name: omada-controller
     image: mbentley/omada-controller:5.1
     environment:
      - TZ=Etc/FR
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8043
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
     network_mode: host

     volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-work:/opt/tplink/EAPController/work
      - omada-logs:/opt/tplink/EAPController/logs
     restart: unless-stopped
volumes:
  omada-data:
  omada-work:
  omada-logs:
